



[root@room9pc01 ~]# python3  --version
Python 3.6.1

[root@room9pc01 ~]# pip3  --version
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

[root@room9pc01 ~]# mkdir   .pip

[root@room9pc01 ~]# vim    .pip/pip.conf

[root@room9pc01 ~]# cat   .pip/pip.conf
[global]
index-url = http://pypi.doubanio.com/simple/
[install]
trusted-host = pypi.doubanio.com
[root@room9pc01 ~]# 


[root@room9pc01 ~]# pip3   install  --upgrade  pip
Collecting pip
  Downloading http://pypi.doubanio.com/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 2.0MB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.1

[root@room9pc01 ~]# pip3   --version
pip 19.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)


[root@room9pc01 ~]# python3  --version
Python 3.6.1


[root@room9pc01 ~]# pip3   install   pymysql

Looking in indexes: http://pypi.doubanio.com/simple/
Collecting pymysql
  Downloading http://pypi.doubanio.com/packages/ed/39/15045ae46f2a123019aa968dfcba0396c161c20f855f11dea6796bcaae95/PyMySQL-0.9.3-py2.py3-none-any.whl (47kB)
     |████████████████████████████████| 51kB 2.5MB/s 
Installing collected packages: pymysql
Successfully installed pymysql-0.9.3
[root@room9pc01 ~]# 


[root@room9pc01 ~]# pip3   install   sqlalchemy

Looking in indexes: http://pypi.doubanio.com/simple/
Collecting sqlalchemy
  Downloading http://pypi.doubanio.com/packages/2b/b2/e6f5c5efc68942edefaa924e8fbea0b32375baa434a511cbf6bb17769cf6/SQLAlchemy-1.3.3.tar.gz (5.9MB)
     |████████████████████████████████| 5.9MB 4.5MB/s 
Installing collected packages: sqlalchemy
  Running setup.py install for sqlalchemy ... done
Successfully installed sqlalchemy-1.3.3
[root@room9pc01 ~]# 


[root@room9pc01 ~]# mkdir   newProjectdir


[root@room9pc01 ~]# cd   newProjectdir/



[root@room9pc01 newProjectdir]# python3.6  -m   venv    newEnv_dir


[root@room9pc01 newProjectdir]# ls
newEnv_dir
[root@room9pc01 newProjectdir]# ls   newEnv_dir/
bin  include  lib  lib64  pyvenv.cfg

[root@room9pc01 newProjectdir]# ls  -a   newEnv_dir/
.  ..  bin  include  lib  lib64  pyvenv.cfg


[root@room9pc01 newProjectdir]# ls   newEnv_dir/bin/
activate      activate.fish  easy_install-3.6  pip3    python   python3.6
activate.csh  easy_install   pip               pip3.6  python3


[root@room9pc01 newProjectdir]# ll  newEnv_dir/bin/activate
-rw-r--r-- 1 root root 2158 4月  26 14:23 newEnv_dir/bin/activate


[root@room9pc01 newProjectdir]# source   newEnv_dir/bin/activate


(newEnv_dir) [root@room9pc01 newProjectdir]# 


(newEnv_dir) [root@room9pc01 newProjectdir]# pip  install  django==1.11.6 

Collecting django==1.11.6
  Downloading http://pypi.doubanio.com/packages/82/33/f9d2871f3aed5062661711bf91b3ebb03daa52cc0e1c37925f3e0c4508c5/Django-1.11.6-py2.py3-none-any.whl (6.9MB)
    100% |████████████████████████████████| 7.0MB 6.4MB/s 
Collecting pytz (from django==1.11.6)
  Downloading http://pypi.doubanio.com/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 10.7MB/s 

Installing collected packages: pytz, django

Successfully installed django-1.11.6 pytz-2019.1
You are using pip version 9.0.1, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


(newEnv_dir) [root@room9pc01 newProjectdir]# pip  install  --upgrade  pip
Collecting pip
  Downloading http://pypi.doubanio.com/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 28.4MB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.1


(newEnv_dir) [root@room9pc01 newProjectdir]# python3  --version
Python 3.6.1

(newEnv_dir) [root@room9pc01 newProjectdir]# pip3   --version
pip 19.1 from /root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/pip (python 3.6)



(newEnv_dir) [root@room9pc01 newProjectdir]# pip   freeze
Django==1.11.6
pytz==2019.1
(newEnv_dir) [root@room9pc01 newProjectdir]# ls
newEnv_dir

(newEnv_dir) [root@room9pc01 newProjectdir]# pip   freeze >  newEnv_dir/pkg.txt

(newEnv_dir) [root@room9pc01 newProjectdir]# ls  newEnv_dir/
bin  include  lib  lib64  pip-selfcheck.json  pkg.txt  pyvenv.cfg


(newEnv_dir) [root@room9pc01 newProjectdir]# cat   newEnv_dir/pkg.txt 
Django==1.11.6
pytz==2019.1
(newEnv_dir) [root@room9pc01 newProjectdir]# python
Python 3.6.1 (default, Mar 20 2018, 00:12:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  django
>>> import    pytz
>>> 
(newEnv_dir) [root@room9pc01 newProjectdir]# type  django-admin
django-admin 是 /root/newProjectdir/newEnv_dir/bin/django-admin


(newEnv_dir) [root@room9pc01 newProjectdir]# django-admin   startproject  mysite
(newEnv_dir) [root@room9pc01 newProjectdir]# ls
mysite  newEnv_dir

(newEnv_dir) [root@room9pc01 newProjectdir]# ls   mysite/
manage.py  mysite

(newEnv_dir) [root@room9pc01 newProjectdir]# cd   mysite/


(newEnv_dir) [root@room9pc01 mysite]# ll   manage.py 
-rwxr-xr-x 1 root root 804 4月  26 14:31 manage.py

(newEnv_dir) [root@room9pc01 mysite]# python    manage.py   runserver   9000


Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fea9d5afe18>
Traceback (most recent call last):
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 31, in <module>
    from pysqlite2 import dbapi2 as Database
ModuleNotFoundError: No module named 'pysqlite2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 33, in <module>
    from sqlite3 import dbapi2 as Database
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/newProjectdir/newEnv_dir/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 35, in <module>
    raise ImproperlyConfigured("Error loading either pysqlite2 or sqlite3 modules (tried in that order): %s" % exc)
django.core.exceptions.ImproperlyConfigured: Error loading either pysqlite2 or sqlite3 modules (tried in that order): No module named '_sqlite3'

^C(newEnv_dir) [root@room9pc01 mysite]# 










